# Generated by Django 3.0.8 on 2020-07-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='descripton',
            new_name='description',
        ),
    ]
